server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=vk_task_tracker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
