server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/vk_task_tracker
    username: vk_postgres_user
    password: vk_postgres_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
